### ISSUE TITLE
Cannot consume artifact

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#272]
I created a consumer/producer setup with DSC v5. I added a resource to the producer and now I'm trying to consume this resource.
Therefore my consumer sends the following request:
```
curl -X 'POST' \
  'http://localhost:8082/api/ids/contract?recipient=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Fids%2Fdata&resourceIds=http%3A%2F%2F172.17.0.1%3A8080%2Fapi%2Foffers%2F71a9d3cd-7088-4424-ae7c-162073abf5f2&artifactIds=http%3A%2F%2Flocalhost%3A8080%2Fapi%2Fartifacts%2Fb5d143e3-80f5-4b52-bf1c-c7839ba484b1&download=false' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '[ {
        "@type" : "ids:Permission",
        "@id" : "http://localhost:8080/api/rules/5041c3e5-4933-419d-87d9-474b98ced678",
        "ids:description" : [ {
          "@value" : "provide-access",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:title" : [ {
          "@value" : "Example Usage Policy",
          "@type" : "http://www.w3.org/2001/XMLSchema#string"
        } ],
        "ids:action" : [ {
          "@id" : "idsc:USE"
        }],
        "ids:target" : "http://localhost:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1"
} ]'
```
The response received by the consumer is:

```
{
  "message": "An error occurred. Please try again later."
}
```
The logs of the consumer is this:
```
2021-05-20T10:18:58,575 [http-nio-8080-exec-9] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T10:18:58,599 [http-nio-8080-exec-9] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T10:18:58,616 [http-nio-8080-exec-9] INFO - URL is valid: http://172.17.0.1:8080/api/ids/data
2021-05-20T10:18:58,616 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,616 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,617 [http-nio-8080-exec-9] INFO - Request is HTTPS: false
2021-05-20T10:18:58,710 [http-nio-8080-exec-9] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T10:18:58,729 [http-nio-8080-exec-9] INFO - URL is valid: http://172.17.0.1:8080/api/ids/data
2021-05-20T10:18:58,730 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,730 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,730 [http-nio-8080-exec-9] INFO - Request is HTTPS: false
2021-05-20T10:18:58,784 [http-nio-8080-exec-9] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T10:18:58,803 [http-nio-8080-exec-9] INFO - URL is valid: http://172.17.0.1:8080/api/ids/data
2021-05-20T10:18:58,804 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,804 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-05-20T10:18:58,804 [http-nio-8080-exec-9] INFO - Request is HTTPS: false
2021-05-20T10:18:58,939 [http-nio-8080-exec-9] ERROR - An unhandled exception has been caught. [exception=(No value present)]
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:148) ~[?:?]
        at io.dataspaceconnector.services.EntityUpdateService.lambda$linkArtifactToAgreement$0(EntityUpdateService.java:170) ~[classes!/:5.0.1]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at io.dataspaceconnector.services.EntityUpdateService.linkArtifactToAgreement(EntityUpdateService.java:170) ~[classes!/:5.0.1]
        at io.dataspaceconnector.controller.messages.ContractRequestMessageController.sendContractRequestMessage(ContractRequestMessageController.java:204) ~[classes!/:5.0.1]
        at io.dataspaceconnector.controller.messages.ContractRequestMessageController$$FastClassBySpringCGLIB$$86360eb.invoke(<generated>) ~[classes!/:5.0.1]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) ~[spring-security-core-5.4.6.jar!/:5.4.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at io.dataspaceconnector.controller.messages.ContractRequestMessageController$$EnhancerBySpringCGLIB$$dd208796.sendContractRequestMessage(<generated>) ~[classes!/:5.0.1]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) [spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) [spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.6.jar!/:5.3.6]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.6.jar!/:5.3.6]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.6.jar!/:5.3.6]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.4.6.jar!/:5.4.6]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.6.jar!/:5.3.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.4.5.jar!/:2.4.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar!/:5.3.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar!/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
The log of the producer is this:
```
2021-05-20T12:18:58,673 [http-nio-8080-exec-8] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T12:18:58,760 [http-nio-8080-exec-9] ERROR - Certificate of the Connector is missing aki/ski extensions!
2021-05-20T12:18:58,820 [http-nio-8080-exec-10] ERROR - Certificate of the Connector is missing aki/ski extensions!
```
But this should not be a problem since both connectors run in idsc:TEST_DEPLOYMENT mode.

I'm kind of stuck because I cannot figure out what the problem could be.

**Comment by juliapampus** [comment]
Have you tried to execute this repeatedly? I have observed that it then works. Could not identitfy a specific reason. I already created an issue for that: https://github.com/International-Data-Spaces-Association/IDS-Connector-Framework/issues/31 @tmberthold

**Comment by ghost** [comment]
Here in this concrete use case with this one concrete exception, it is thrown by an unchecked call to a `get()` on a possible `null `result by `identifyByRemoteId(x)`. This `null.get()` throws the exception shown above, which is not caught further in the code. Java also points out `Optional get() without isPresent()`, which would address exactly the above `NoSuchElementException`.

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/7359b11e274e9c78a390dc04cfeef269f310d66a/src/main/java/io/dataspaceconnector/services/EntityUpdateService.java#L170

We still look at the general certificate access issues.

**Comment by sebplorenz** [comment]
@tmberthold Can you replace the line you mentioned with:
```
.map(x -> artifactService.identifyByRemoteId(x)
                        .orElseThrow(() -> new ResourceNotFoundException("The artifact with remote id " + x + " could not be found in the database.")))
```
and in ResourceNotFoundExcpeptionHandler line 55:
```
body.put("message", ((exception != null) ? exception.getMessage() : "Resource not found"));
```
then the problem can easily be seen in the client. Without going through the logs.

Anyway it doesn't explain to me why the consumer connector is looking for the artifact in the local database at the time when the contract for this artifact is negotiated. The artifact has not been created before. Or should it have been created in the process of contract negotiation?

**Comment by ghost** [comment]
Please refer to @juliapampus . Of course, this could be the reason, but I think she knows better than me about the DSC.

**Comment by sebplorenz** [comment]
I found the error in my query from above. I set the recipient URL to 
http://**172.17.0.1**:8080/api/ids/data and I'm requesting the artifact with URI 
http://**localhost**:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1

The consumer gets the artifact returned and saves it in its local database with this URI
http://172.17.0.1:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1

When it is then searching for the artifact in its local database it tries to find
http://localhost:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1 but only has
http://172.17.0.1:8080/api/artifacts/b5d143e3-80f5-4b52-bf1c-c7839ba484b1
which is not equal.

If the artifact URI is wrong I would expect the connector to not download it and present a message like "The requested artifact x is not available on server y."
