### ISSUE TITLE
Unauthorized when creating an artifiact with username and password using provided scripts

### ISSUE THREAD

**Issue by PaulThomas42** [FraunhoferISST/DataspaceConnector#297]
**Describe the bug**
When creating an artifact using the provided script provider_consumer_single_artifact_single_policy.py whilst running two connectors at localhost, port 8080 and 8081, the credential fields for username and password seem to be ignored when trying to access a remote data source.

**To Reproduce**
1. Enter artifact details inside the create_artifact() method, for a remote data source that needs basic authorization by supplying the fields:
```
  "accessUrl":"https://Example.com",
  "username": "testusr",
  "password": "testpwd"
```
inside the json part of the method. 
2. When running the script this should lead to the message: 
```
"b'Ids message handling failed. Message could not be sent.'"
```
and the an Exception in the IDE(Eclipse in my case):
```
Caused by: java.io.IOException: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://Example.com} With Body: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at de.fraunhofer.isst.ids.framework.communication.http.HttpServiceImpl.sendRequest(HttpServiceImpl.java:144) ~[base-4.0.7.jar:?]
	at de.fraunhofer.isst.ids.framework.communication.http.HttpServiceImpl.get(HttpServiceImpl.java:75) ~[base-4.0.7.jar:?]
	at io.dataspaceconnector.services.HttpService.get(HttpService.java:129) ~[classes/:?]
	at io.dataspaceconnector.services.HttpService.get(HttpService.java:177) ~[classes/:?]
	at io.dataspaceconnector.services.resources.ArtifactService.getData(ArtifactService.java:286) ~[classes/:?]
	... 126 more
```
**Expected behavior**
Connecting to remote data source with given credentials.

**Comment by brianjahnke** [comment]
Hi, 

i can reproduce your problem.

Setup:
- Create an artifact with a remote backend.
- The backend is another connector.
- The accessUrl is the private description of the backend connector.

**Comment by sebplorenz** [comment]
Hi, I've tested with the 297 branch and I am now able to download the data. But the data is in a binary format. The documentation states: "... the requested and downloaded data will be stored in the database as a bytestream and is automatically decoded on an API call." If I click the download button in the swagger client I'm getting a binary. The DSC does not throw any exception in the logs. Is there something wrong with the decoding?
