### ISSUE TITLE
swagger-ui doesn't load with server.ssl.enabled=true

### ISSUE THREAD

**Issue by AngWickert** [FraunhoferISST/DataspaceConnector#394]
I've changed the application.properties under HTTP/S to
server.ssl.enabled=true

and move the resulting jar-File to our Linux-server for starting it there. While trying to open the swagger-ui in the browser (chrome, firefox) the following error message appears:

`2021-07-05T14:09:43,537 [scheduling-1] INFO - Scanning agreements...
2021-07-05T14:09:53,948 [http-nio-8443-exec-2] INFO - Error parsing HTTP request header\n Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030x950x8fQ0xfc0x190x8d0x1f0x0fE0x1d0xecks0x980x15^0xda0x1b0xa00x140xf80x950x85aA0x8fq0xd20x020xb80x89% ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.46.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) [tomcat-embed-core-9.0.46.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.46.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.46.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.46.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.46.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.46.jar!/:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-07-05T14:09:54,033 [http-nio-8443-exec-1] INFO - Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-07-05T14:09:54,033 [http-nio-8443-exec-1] INFO - Initializing Servlet 'dispatcherServlet'
2021-07-05T14:09:54,037 [http-nio-8443-exec-1] INFO - Completed initialization in 4 ms
2021-07-05T14:10:43,564 [scheduling-1] INFO - Scanning agreements...
`
When starting the same file at localhost, everything works fine.

**Comment by AngWickert** [comment]
bug is fixed with version 6.0.0
