### ISSUE TITLE
Error on PUT ​/api​/configurations​/{id}

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/DataspaceConnector#444]
When I call PUT ​/api​/configurations​/{id} with "authentication" block for proxy (u can use the Swagger example), I get the error:

2021-07-19T12:14:58,350 [https-jsse-nio-8080-exec-6] ERROR - Referentielle Integrit├ñt verletzt: "FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"\nReferential integrity constraint violation: "FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"; SQL statement:\ndelete from authentication where id=? [23503-200]
2021-07-19T12:14:58,350 [https-jsse-nio-8080-exec-6] ERROR - Referentielle Integrit├ñt verletzt: "FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"\nReferential integrity constraint violation: "FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"; SQL statement:\ndelete from authentication where id=? [23503-200]
2021-07-19T12:14:58,370 [https-jsse-nio-8080-exec-6] ERROR - An unhandled exception has been caught. [exception=(could not execute statement; SQL [n/a]; constraint ["FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"; SQL statement:\ndelete from authentication where id=? [23503-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement)]
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["FKJQODC488DRFB2MRR31DNI7EU4: PUBLIC.PROXY FOREIGN KEY(AUTHENTICATION_ID) REFERENCES PUBLIC.AUTHENTICATION(ID) (1)"; SQL statement:
delete from authentication where id=? [23503-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276) ~[spring-orm-5.3.8.jar!/:5.3.8]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.8.jar!/:5.3.8]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551) ~[spring-orm-5.3.8.jar!/:5.3.8]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174) ~[spring-data-jpa-2.5.2.jar!/:2.5.2]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at com.sun.proxy.$Proxy170.saveAndFlush(Unknown Source) ~[?:?]
        at io.dataspaceconnector.service.resource.BaseEntityService.persist(BaseEntityService.java:167) ~[classes!/:6.0.0]
        at io.dataspaceconnector.service.resource.BaseEntityService.update(BaseEntityService.java:94) ~[classes!/:6.0.0]
        at io.dataspaceconnector.service.resource.BaseEntityService$$FastClassBySpringCGLIB$$fc606ef.invoke(<generated>) ~[classes!/:6.0.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at io.dataspaceconnector.service.configuration.ConfigurationService$$EnhancerBySpringCGLIB$$17c23760.update(<generated>) ~[classes!/:6.0.0]
        at io.dataspaceconnector.controller.resource.BaseResourceController.update(BaseResourceController.java:125) ~[classes!/:6.0.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]

**Comment by brianjahnke** [comment]
Should be fixed on 255. Please verify.

**Comment by BastianWel** [comment]
Works now.
