### ISSUE TITLE
Policy connector-restriction not working

### ISSUE THREAD

**Issue by gregors101** [FraunhoferISST/DataspaceConnector#472]
**Describe the bug**
The policy is not working. While the usage check on provider side, the check compares the id of the consumer connector with the id of the consumer connector set into the policy. 

**To Reproduce**
1. Provider: create data with policy connector-restriction
e.g. 
{
  "ids:constraint": [
    {
      "@type": "ids:Constraint",
      "@id": "https://w3id.org/idsa/autogen/constraint/e792d378-c15c-4d4e-ae22-274ab6a8ac11",
      "ids:operator": {
        "@id": "https://w3id.org/idsa/code/SAME_AS"
      },
      "ids:leftOperand": {
        "@id": "https://w3id.org/idsa/code/SYSTEM"
      },
      "ids:rightOperand": {
        "@value": "https://w3id.org/idsa/baseConnector/Consumer-Connector-Id/1234455555",
        "@type": "http://www.w3.org/2001/XMLSchema#anyURI"
      }
    }
  ]
}
2. Consumer: request agreement - does not work because of policy mismatch

**Expected behavior**
agreement request should be possible

**Screenshots & Logs**
See the issuer, there is a mismatch with the connector id of the policy

2021-07-29T12:29:15,773 [https-jsse-nio-8020-exec-5] DEBUG - Policy restriction detected. [exception=(Policy restriction detected.), artifact=(https://localhost:8020/api/artifacts/33a7983d-1f47-4e4a-84a6-8b1ea793d217), contract=(https://localhost:8020/api/agreements/e399a13b-4354-4238-95ca-6cfe8f00120a), **issuer**=**(https://w3id.org/idsa/autogen/baseConnector/b85dd0fa-3fec-4c6e-ba43-e9af586f5e38**), messageId=(https://w3id.org/idsa/autogen/artifactRequestMessage/5d07dcd8-eed1-4e3a-b571-4045654f5b58)]
io.dataspaceconnector.exception.PolicyRestrictionException: Policy restriction detected.
	at io.dataspaceconnector.camel.processor.handler.PolicyValidator.processInternal(IdsValidator.java:186) ~[classes/:?]
	at io.dataspaceconnector.camel.processor.handler.PolicyValidator.processInternal(IdsValidator.java:147) ~[classes/:?]

**Desktop (please complete the following information):**
 - Version (DSC) 6.0.0

**Comment by trueg** [comment]
It is strange. I experience the exact opposite. Despite my SYSTEM-based constraint similar to yours any connector gets an agreement and can fetch the data.

**Comment by juliapampus** [comment]
Tested. Working with v6.2.0.
