### ISSUE TITLE
Unable to run policy negotation script on bootstrapped resources

### ISSUE THREAD

**Issue by juliapampus** [FraunhoferISST/DataspaceConnector#496]
**Describe the bug**
Setting `bootstrap.enabled=true` in the `application.properties`, the connector is not able to negotiate the created artifact.

**To Reproduce**
1. Set `bootstrap.enabled=true` in `application.properties`.
2. Modify [this](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/scripts/tests/legacy/contract_negotiation_allow_access.py) script to skip the providing resource part and directly move on to the consumer requests.
3. See `Received invalid ids message.` as a response.

**Expected behavior**
An agreement as the response when executing the script.

**Screenshots & Logs**
```
2021-08-05T10:28:42,881 [https-jsse-nio-8080-exec-10] WARN - Language not valid: https://w3id.org/idsa/code/en
2021-08-05T10:28:42,881 [https-jsse-nio-8080-exec-10] WARN - Language not valid: https://w3id.org/idsa/code/en
2021-08-05T10:28:42,881 [https-jsse-nio-8080-exec-10] WARN - Language not valid: https://w3id.org/idsa/code/en
```

**Desktop (please complete the following information):**
 - Version (DSC): v6.0.0

**Comment by sebplorenz** [comment]
After talking to  @brianjahnke I have updated the config.json in my example with a v6.0.0 config and I tried to do the contract negotiation with the provided script (https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/scripts/tests/contract_negotation_allow_access.py).

The script shows the following error:
```
/usr/bin/python3.8 /home/sebp/workspace/DataspaceConnector_v6/scripts/tests/contract_negotation_allow_access.py
Starting script
Created provider resources
Traceback (most recent call last):
  File "/home/sebp/workspace/DataspaceConnector_v6/scripts/tests/contract_negotation_allow_access.py", line 77, in <module>
    offer = consumer.descriptionRequest(provider_alias + "/api/ids/data", offers)
  File "/home/sebp/workspace/DataspaceConnector_v6/scripts/tests/idsapi.py", line 41, in descriptionRequest
    return json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
```

**Comment by HeinrichPet** [comment]
Workaround: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/505#issuecomment-898314100
