### ISSUE TITLE
Contract negotiation fails with DSC 6 (provider-consumer deployment example)

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#505]
**Describe the bug**
Contract negotiation not working in version 6.

**To Reproduce**
1. Use provider consumer example from the deployment examples and set the version of both connectors to 6.0.0 in the docker-compose.yml file
2. docker-compose up -d
3. Create the resource using the script create_resource.sh
4. Do the manual steps to consume the resource or run the tests in this postman collection https://raw.githubusercontent.com/agarciagan/IDS-Deployment-Examples/feature/provider_consumer_postman/dataspace-connector/provider-consumer/prov_cons.postman_collection
5. When trying to negotiate a contract, the following error occurs in the swagger UI: 'Received invalid agreement during negotiation phase.'
The log of the consumer contains this:
```
2021-08-10T09:31:28,750 [http-nio-8080-exec-9] ERROR - JWT strings must contain exactly 2 period characters. Found: 0
2021-08-10T09:31:28,750 [http-nio-8080-exec-9] WARN - Could not parse jwt!
2021-08-10T09:31:28,752 [http-nio-8080-exec-9] WARN - TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, will not be send in PRODUCTIVE_DEPLOYMENT, reason: Mandatorily required information of the connector certificate is missing (AKI/SKI)!
2021-08-10T09:31:28,792 [http-nio-8080-exec-9] ERROR - JWT strings must contain exactly 2 period characters. Found: 0
2021-08-10T09:31:28,792 [http-nio-8080-exec-9] WARN - Could not parse jwt!
2021-08-10T09:31:28,793 [http-nio-8080-exec-9] WARN - TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, will not be send in PRODUCTIVE_DEPLOYMENT, reason: Mandatorily required information of the connector certificate is missing (AKI/SKI)!
2021-08-10T09:31:28,824 [http-nio-8080-exec-9] INFO - URL is valid: http://provider:8080/api/ids/data
2021-08-10T09:31:28,825 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-08-10T09:31:28,825 [http-nio-8080-exec-9] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-08-10T09:31:28,825 [http-nio-8080-exec-9] INFO - Request is HTTPS: false
2021-08-10T09:31:29,019 [http-nio-8080-exec-9] INFO - {\n  "@context" : {\n    "ids" : "https://w3id.org/idsa/core/",\n    "idsc" : "https://w3id.org/idsa/code/"\n  },\n  "@type" : "ids:ContractAgreementMessage",\n  "@id" : "https://w3id.org/idsa/autogen/contractAgreementMessage/e10f0966-8874-4992-bfa0-debf0872e840",\n  "ids:modelVersion" : "4.0.10",\n  "ids:issued" : {\n    "@value" : "2021-08-10T09:31:28.998Z",\n    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"\n  },\n  "ids:correlationMessage" : {\n    "@id" : "https://w3id.org/idsa/autogen/contractRequestMessage/f460e46c-fdb6-4707-bf77-cd63b78ace80"\n  },\n  "ids:issuerConnector" : {\n    "@id" : "https://w3id.org/idsa/autogen/baseConnector/provider"\n  },\n  "ids:recipientConnector" : [ {\n    "@id" : "https://w3id.org/idsa/autogen/baseConnector/consumer"\n  } ],\n  "ids:senderAgent" : {\n    "@id" : "https://w3id.org/idsa/autogen/baseConnector/provider"\n  },\n  "ids:securityToken" : {\n    "@type" : "ids:DynamicAttributeToken",\n    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/d0c5827e-3408-4da2-b0ae-029cb1bb3cbd",\n    "ids:tokenFormat" : {\n      "@id" : "https://w3id.org/idsa/code/JWT"\n    },\n    "ids:tokenValue" : "INVALID_TOKEN"\n  }\n}
2021-08-10T09:31:29,032 [http-nio-8080-exec-9] INFO - Received response passed SHACL Validation.
2021-08-10T09:31:29,052 [http-nio-8080-exec-9] WARN - Could not deserialize Playload Could not transform input to an appropriate implementing class for de.fraunhofer.iais.eis.Connector
2021-08-10T09:31:29,052 [http-nio-8080-exec-9] WARN - Skipping Connector-SecurityProfile Attribute!
```

**Expected behavior**
Contract should be accepted from both sides. The example was working with DSC version 5.1.2.

**Additional info**
From the logs, it looks like the consumer cannot parse the contract agreement message coming from the provider.

**Comment by sebplorenz** [comment]
After talking to  @brianjahnke I have updated the config.json in my example with a v6.0.0 config and I tried to do the contract negotiation with the provided script (https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/scripts/tests/contract_negotation_allow_access.py).

The script shows the following error:
```
/usr/bin/python3.8 /home/sebp/workspace/DataspaceConnector_v6/scripts/tests/contract_negotation_allow_access.py
Starting script
Created provider resources
Traceback (most recent call last):
  File "/home/sebp/workspace/DataspaceConnector_v6/scripts/tests/contract_negotation_allow_access.py", line 77, in <module>
    offer = consumer.descriptionRequest(provider_alias + "/api/ids/data", offers)
  File "/home/sebp/workspace/DataspaceConnector_v6/scripts/tests/idsapi.py", line 41, in descriptionRequest
    return json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
```

**Comment by sebplorenz** [comment]
Got it. The ports were missing in the script. Now the script works and the consumer can consume the resource. Now the question is what the python script is doing different compared to the postman script.

**Comment by brianjahnke** [comment]
Hi, 
sounds great! 
Without looking at postman: The python scripts replaces the provider url with the provider_alias url, could that be a difference?

**Comment by sebplorenz** [comment]
Because I don't find the reason why the contract negotiation only works with the python script, I tried to create my resource with the bootstrapping method described here: https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Bootstrapping
This method does not work too. A contract agreement for the example resource from the bootstrapping example cannot be created.

**Comment by juliapampus** [comment]
This problem is known: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/496 

Did you maybe miss the `ids:target` for the contract request in the Swagger UI? @sebplorenz

**Comment by sebplorenz** [comment]
No, I didn't miss the ids:target.

**Comment by sebplorenz** [comment]
But if I create a resource with the script from the provider-consumer-example and experience the same bug as described in #496, then there seems to be a bug either in how the rule/permission is created/stored at the provider side or in the contract negotiation sequence.

**Comment by sebplorenz** [comment]
If I remove this part from the catalog example from the bootstrap docs (https://international-data-spaces-association.github.io/DataspaceConnector/Deployment/Bootstrapping):
```
"ids:resourceEndpoint": [
        {
          "@type": "ids:ConnectorEndpoint",
          "@id": "https://w3id.org/idsa/autogen/connectorEndpoint/4458078e-c2f2-4d9f-afbe-54e9daa4c1b8",
          "ids:accessURL": "https://exampleaccessURL.com"
        }
      ],
```
then the bootstrap method works and the agreement is created successfully.
