### ISSUE TITLE
Connector Offline error in Kubernetes deployment

### ISSUE THREAD

**Issue by dileep-ramachandrarao** [FraunhoferISST/DataspaceConnector#548]
**Describe the bug**
The DSC v6.1.0 is deployed in the Kubernetes cluster. 

The connector status is set to online in the config.json file
```
"ids:connectorStatus" : {
    "@id" : "idsc:CONNECTOR_ONLINE" 
}
```

But, when trying to access the connector, it throws the following error:
```
{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/TEMPORARILY_NOT_AVAILABLE"
  },
  "payload": "This connector is offline and will not process any ids requests.",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```

In docker, it works fine. But, the above error is only noticed when deployed in the Kubernetes cluster.

**Comment by HeinrichPet** [comment]
Hi,
some questions to get more details:
- Are there any logs?
- Do you start it with a fresh DB?
- Are you sure that the changed config.json is loaded?

**Comment by dileep-ramachandrarao** [comment]
>     * Are there any logs?

The logs on the consumer side: 

```
2021-08-31T13:56:21,125 [https-jsse-nio-8080-exec-3] WARN - TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, will not be sent in PRODUCTIVE_DEPLOYMENT, reason: Mandatory required information of the connector certificate is missing (AKI/SKI)! Needed to determine the fingerprint of the connector for the DAPS! Possible reason: Are you using a valid connector certificate issued by the DAPS?
2021-08-31T13:56:21,174 [https-jsse-nio-8080-exec-3] WARN - TEST_DEPLOYMENT: IDS-Message is sent without a valid DAT, will not be sent in PRODUCTIVE_DEPLOYMENT, reason: Mandatory required information of the connector certificate is missing (AKI/SKI)! Needed to determine the fingerprint of the connector for the DAPS! Possible reason: Are you using a valid connector certificate issued by the DAPS?
2021-08-31T13:56:21,233 [https-jsse-nio-8080-exec-3] INFO - Sending request to https://provider.dsc-v6.ids-dev.shoot.canary.k8s-hana.ondemand.com/api/ids/data ...
2021-08-31T13:56:24,698 [https-jsse-nio-8080-exec-3] INFO - Successfully received response to request.
2021-08-31T13:56:24,877 [https-jsse-nio-8080-exec-3] INFO - Successfully passed SHACL-Validation.
2021-08-31T13:56:24,945 [https-jsse-nio-8080-exec-3] ERROR - [line: 1, col: 5 ] Unrecognized token 'This': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
2021-08-31T13:56:24,994 [https-jsse-nio-8080-exec-3] WARN - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/TEMPORARILY_NOT_AVAILABLE, payload=This connector is offline and will not process any ids requests., type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```


The logs on the provider side:
```
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.5.4.jar!/:2.5.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189) [opentracing-web-servlet-filter-0.4.0.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.52.jar!/:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.52.jar!/:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-08-31T13:56:24,535 [https-jsse-nio-8080-exec-8] WARN - Transaction rollback (0x1828ab51) redelivered(false) for (MessageId: 232A26166E81FBA-0000000000000000 on ExchangeId: 232A26166E81FBA-0000000000000000) caught: io.dataspaceconnector.service.message.handler.exception.ConnectorOfflineException
```

>     * Do you start it with a fresh DB?
Yes 

>     * Are you sure that the changed config.json is loaded?
Yes

**Comment by brianjahnke** [comment]
Hi,
are you sure the DB is clean? Sometimes the PVCs like to stick around.
I am asking, because I just followed this [link](https://provider.dsc-v6.ids-dev.shoot.canary.k8s-hana.ondemand.com/) in your logs and the connector is using version 4.0.0 and 4.1.0 as inbound and version 4.1.0 as outbound model on a connector with version 6.1.3.
The official release of 6.1.3 contains a different infomodel [set](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/v6.1.3/src/main/resources/conf/config.json).

**Comment by dileep-ramachandrarao** [comment]
Hi,
Thanks for the hint. After deleting the PVCs and restarting the DB, the issue was resolved. On the other hand, it was a fresh installation and I didn't think about clearing the pvc. Anyways, the issue is resolved and thanks for the help. I would close the issue.
