### ISSUE TITLE
DSC logs stack traces if DAPS is down

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#633]
If the DAPS is down then huge stack traces appear in the logs. Like:

```
2021-09-29T15:30:00.648685575+02:00 2021-09-29 13:30:00,648 https-jsse-nio-8080-exec-8 WARN  io.dataspaceconnector.common.ids.ConnectorService - Connection to DAPS could not be established. [exception=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): connect timed out)]
2021-09-29T15:30:00.664434333+02:00 2021-09-29 13:30:00,661 https-jsse-nio-8080-exec-8 WARN  io.dataspaceconnector.service.message.builder.type.base.AbstractMessageService - Failed to build ids message.[exception=(null)]
2021-09-29T15:30:00.664450143+02:00 de.fraunhofer.iais.eis.util.ConstraintViolationException: null
2021-09-29T15:30:00.664452527+02:00 	at de.fraunhofer.iais.eis.validate.BeanValidatorImpl.validate(BeanValidatorImpl.java:24) ~[validation-serialization-provider-4.2.0.jar!/:?]
2021-09-29T15:30:00.664454150+02:00 	at de.fraunhofer.iais.eis.util.VocabUtil.validate(VocabUtil.java:68) ~[util-4.2.0.jar!/:?]
2021-09-29T15:30:00.664455713+02:00 	at de.fraunhofer.iais.eis.ArtifactRequestMessageBuilder.build(ArtifactRequestMessageBuilder.java:188) ~[java-4.2.0.jar!/:?]
2021-09-29T15:30:00.664457196+02:00 	at io.dataspaceconnector.service.message.builder.type.ArtifactRequestService.buildMessage(ArtifactRequestService.java:91) ~[classes!/:6.2.0]
2021-09-29T15:30:00.664458669+02:00 	at io.dataspaceconnector.service.message.builder.type.ArtifactRequestService.buildMessage(ArtifactRequestService.java:48) ~[classes!/:6.2.0]
2021-09-29T15:30:00.664460111+02:00 	at io.dataspaceconnector.service.message.builder.type.base.AbstractMessageService.send(AbstractMessageService.java:105) [classes!/:6.2.0]
2021-09-29T15:30:00.664461494+02:00 	at io.dataspaceconnector.service.message.builder.type.ArtifactRequestService.sendMessage(ArtifactRequestService.java:150) [classes!/:6.2.0]
2021-09-29T15:30:00.664462927+02:00 	at io.dataspaceconnector.service.BlockingArtifactReceiver.retrieve(BlockingArtifactReceiver.java:113) [classes!/:6.2.0]
2021-09-29T15:30:00.664473065+02:00 	at io.dataspaceconnector.service.resource.type.ArtifactService.downloadAndUpdateData(ArtifactService.java:262) [classes!/:6.2.0]
2021-09-29T15:30:00.664474789+02:00 	at io.dataspaceconnector.service.resource.type.ArtifactService.getData(ArtifactService.java:236) [classes!/:6.2.0]
2021-09-29T15:30:00.664476231+02:00 	at io.dataspaceconnector.service.resource.type.ArtifactService.tryToAccessDataByUsingAnyAgreement(ArtifactService.java:185) [classes!/:6.2.0]
2021-09-29T15:30:00.664477654+02:00 	at io.dataspaceconnector.service.resource.type.ArtifactService.getData(ArtifactService.java:160) [classes!/:6.2.0]
2021-09-29T15:30:00.664479066+02:00 	at io.dataspaceconnector.service.resource.type.ArtifactService$$FastClassBySpringCGLIB$$99ead9e1.invoke(<generated>) [classes!/:6.2.0]
2021-09-29T15:30:00.664480539+02:00 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.9.jar!/:5.3.9]
2021-09-29T15:30:00.664483274+02:00 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) [spring-aop-5.3.9.jar!/:5.3.9]
... and a lot more
```

**Comment by vdakker** [comment]
Seems like the log level of the exceptions is sometimes set to `DEBUG` and sometimes to `WARN` in the `catch` clauses of `AbstractMessageService.send`:

```java
...
} catch (SerializeException | ConstraintViolationException e) {
            final var msg = ErrorMessage.MESSAGE_BUILDING_FAILED;
            if (log.isWarnEnabled()) {
                log.warn(msg + "[exception=({})]", e.getMessage(), e);
            }
            throw new MessageException(msg, e);
} catch (MultipartParseException | DeserializeException | ShaclValidatorException e) {
            final var msg = ErrorMessage.INVALID_MESSAGE;
            if (log.isDebugEnabled()) {
                log.debug(msg + " [exception=({})]", e.getMessage(), e);
            }
            throw new MessageResponseException(msg, e);
...
```

**Comment by juliapampus** [comment]
Printing out the stack trace at log level warn and debug was a design decision to provide the possibility to find errors more easily.

**Comment by juliapampus** [comment]
Nevertheless, we will include a null checking before building a message to avoid especially this error.
