### ISSUE TITLE
Error parsing HTTP request header (HTTPS request to HTTP connector)

### ISSUE THREAD

**Issue by ghost** [FraunhoferISST/DataspaceConnector#737]
**Describe the bug**
An error message is shown when trying to access a non-SSL DSC (running locally) over HTTPS.

**To Reproduce**
1. Clone current `main` branch
2. Edit `application.properties` and disable SSL (`server.ssl.enabled=false`)
3. Start the DSC via docker-compose (`docker-compose up --build`)
4. After the DSC is running, open a browser and go to `https://localhost:8080`
5. The error message is shown.

**Expected behavior**
No error message in the logs.

**Screenshots & Logs**
```
[http-nio-8080-exec-1] INFO - Error parsing HTTP request header\n Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03n00xb90xb40xd70x850xaf0xbf0xbd0x170x150x93/0xc50x1b0x8d0x13k0x1e0x160xd9Vt0x830x8a0x9b0xb14A00xf0} ]. HTTP method names must be tokens
  at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.54.jar!/:?]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.54.jar!/:?]
  at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Desktop (please complete the following information):**
 - OS: Windows 10 + Docker
 - Browser: Chrome
 - Version (DSC): Latest `main` branch (`6.6.0-SNAPSHOT`)

**Additional context**
The error message is only displayed one time. When trying to visit `https://localhost.8080` again, it isn't displayed for a second time.

**Comment by brianjahnke** [comment]
Hi,

when disabling SSL spring cannot decrypt the http header. Thus the **Info** - Message is shown.
