### ISSUE TITLE
Strange communication error logged as INFO?

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#781]
When requesting a self-description from the remote db connector I'm having the following logs in the local connector:

```
2021-12-08T09:37:28,745 [http-nio-8080-exec-3] WARN - Received response but response-code not in 200-299. [code=(400)]
2021-12-08T09:37:28,775 [http-nio-8080-exec-3] INFO - Successfully passed SHACL-Validation.
2021-12-08T09:37:28,796 [http-nio-8080-exec-3] INFO - Executed query: PREFIX ids: <https://w3id.org/idsa/core/>\nSELECT ?securityToken ?authorizationToken ?correlationMessage (GROUP_CONCAT(?recipientConnector;separator="||") AS ?recipientConnectors)  ?issuerConnector ?senderAgent ?modelVersion ?rejectionReason ?issued ?contentVersion ?transferContract (GROUP_CONCAT(?recipientAgent;separator="||") AS ?recipientAgents)  {  <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> a ids:RejectionMessage.  <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:securityToken ?securityToken . OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:authorizationToken ?authorizationToken .}  <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:correlationMessage ?correlationMessage . OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:recipientConnector ?recipientConnector .}  <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:issuerConnector ?issuerConnector . <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:senderAgent ?senderAgent . <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:modelVersion ?modelVersion . OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:rejectionReason ?rejectionReason .}  <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:issued ?issued . OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:contentVersion ?contentVersion .}  OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:transferContract ?transferContract .}  OPTIONAL { <https://w3id.org/idsa/autogen/rejectionMessage/f7e5029c-9f18-4a98-9d80-9d9f30c46261> ids:recipientAgent ?recipientAgent .}  } GROUP BY ?securityToken ?authorizationToken ?correlationMessage ?issuerConnector ?senderAgent ?modelVersion ?rejectionReason ?issued ?contentVersion ?transferContract
```
The local connector is of version 6.3.1.
The db connector is of version 6.2.0.
There is no error log in the requested connector.

**Comment by juliapampus** [comment]
@tmberthold

**Comment by ghost** [comment]
Hello!
The warning is an indication that the received response did not arrive within the HTTP status code range successful. 
Here in this case the response had the HTTP-Statuscode 400 Bad Request.
Since we as Dataspace Connector try to process the response anyway, regardless of the HTTP status code of the response, we only issue a warning here that a response with HTTP status codes != successful-range arrived and still try to process it anyway.
Here it would be necessary to check the sender of the response why he responds with BAD_REQUEST, if this did not correspond to the expected response-code.

**Comment by ghost** [comment]
As for the third log message, unfortunately I can't track where that log comes from. I always end up in the SPARQL/SHACL area, where this kind of strings are assembled and used.

Seems to me that the sender of the response answered with 400 BAD_REQUEST and a RejectionMessage.

**Comment by ip312** [comment]
Hi! The error seems to be reproducible for the DB Connector. The error code in the Swagger UI is 502 (Bad Gateway)
In my log the response is successfully received. 

> 2021-12-08T15:23:50,819 [https-jsse-nio-8080-exec-5] INFO  Successfully received response to request.
2021-12-08T15:23:50,860 [https-jsse-nio-8080-exec-5] INFO  Initializing SHACL shapes.
2021-12-08T15:23:51,423 [https-jsse-nio-8080-exec-5] INFO  Loading SHACL shapes from resources. You can optionally download the latest shapes from GitHub.
2021-12-08T15:23:52,787 [https-jsse-nio-8080-exec-5] INFO  Loading ontology from resources
2021-12-08T15:23:52,866 [https-jsse-nio-8080-exec-5] INFO  Initialization of SHACL shapes complete.
2021-12-08T15:23:52,951 [https-jsse-nio-8080-exec-5] INFO  Successfully passed SHACL-Validation.
2021-12-08T15:23:52,965 [scheduling-1] INFO  Scanning agreements...
2021-12-08T15:23:53,039 [https-jsse-nio-8080-exec-5] INFO  Executed query: PREFIX ids: <https://w3id.org/idsa/core/>\nSELECT ?authorizationToken ?securityToken ?correlationMessage (GROUP_CONCAT(?recipientConnector;separator="||") AS ?recipientConnectors)  ?issuerConnector ?senderAgent ?modelVersion ?issued ?contentVersion ?transferContract (GROUP_CONCAT(?recipientAgent;separator="||") AS ?recipientAgents)  {  <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> a ids:DescriptionResponseMessage.  OPTIONAL { <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:authorizationToken ?authorizationToken .}  <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:securityToken ?securityToken . <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:correlationMessage ?correlationMessage . OPTIONAL { <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:recipientConnector ?recipientConnector .}  <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:issuerConnector ?issuerConnector . <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:senderAgent ?senderAgent . <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:modelVersion ?modelVersion . <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:issued ?issued . OPTIONAL { <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:contentVersion ?contentVersion .}  OPTIONAL { <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:transferContract ?transferContract .}  OPTIONAL { <https://w3id.org/idsa/autogen/descriptionResponseMessage/363ae933-65e3-40a4-89ec-7328bc6abef9> ids:recipientAgent ?recipientAgent .}  } GROUP BY ?authorizationToken ?securityToken ?correlationMessage ?issuerConnector ?senderAgent ?modelVersion ?issued ?contentVersion ?transferContract
2021-12-08T15:23:53,040 [https-jsse-nio-8080-exec-5] DEBUG Received invalid ids message. [exception=(java.io.IOException: The following mandatory field(s) of DescriptionResponseMessage are not filled or invalid: ids:securityToken, ids:correlationMessage, ids:issuerConnector, ids:senderAgent, ids:modelVersion, ids:issued. Note that the value of "@id" fields MUST be a valid URI (e.g. emails preceded by "mailto:"). Mandatory fields are: securityToken, correlationMessage, issuerConnector, senderAgent, modelVersion, issued)]
de.fraunhofer.ids.messaging.common.DeserializeException: java.io.IOException: The following mandatory field(s) of DescriptionResponseMessage are not filled or invalid: ids:securityToken, ids:correlationMessage, ids:issuerConnector, ids:senderAgent, ids:modelVersion, ids:issued. Note that the value of "@id" fields MUST be a valid URI (e.g. emails preceded by "mailto:"). Mandatory fields are: securityToken, correlationMessage, issuerConnector, senderAgent, modelVersion, issued
	at de.fraunhofer.ids.messaging.protocol.http.IdsHttpService.checkDatFromResponse(IdsHttpService.java:176) ~[messaging-5.0.1.jar!/:?]
	at de.fraunhofer.ids.messaging.protocol.http.IdsHttpService.sendAndCheckDat(IdsHttpService.java:504) ~[messaging-5.0.1.jar!/:?]
	at io.dataspaceconnector.service.message.builder.type.base.AbstractMessageService.send(AbstractMessageService.java:112) [classes!/:6.3.1]
	at io.dataspaceconnector.service.message.builder.type.DescriptionRequestService.sendMessage(DescriptionRequestService.java:92) [classes!/:6.3.1]
	at io.dataspaceconnector.controller.message.ids.DescriptionRequestMessageController.sendMessage(DescriptionRequestMessageController.java:128) [classes!/:6.3.1]
	at io.dataspaceconnector.controller.message.ids.DescriptionRequestMessageController$$FastClassBySpringCGLIB$$ba843bd6.invoke(<generated>) [classes!/:6.3.1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.10.jar!/:5.3.10]

**Comment by ghost** [comment]
Unfortunately I don't know much about the setup of the DB Connector, I would locate the problem there as it responds in the first example with `400 BAD_REQUEST` in the second example above with `502 BAD_GATEWAY`.

As for the `Successfully received response to request.` message in the second example, it could be that the Swagger UI displays the output of an HTML error page which just displays "502 BAD_GATEWAY", but the response including the HTML page was packed into a status code between 200-299 and therefore the message of the successful response in the logs, although it contains a 502 BAD_GATEWAY as body/payload.

**Comment by sebplorenz** [comment]
But this is another problem. In the error logs it says response code 400 as can be seen here:
```
2021-12-09T12:33:35,375 [http-nio-8080-exec-6] INFO - Sending request to https://ids.db-connector.mobilitydataspace.io/api/ids/data ...
2021-12-09T12:33:35,695 [http-nio-8080-exec-6] ERROR - Received response but response-code not in 200-299! Response-code: 400!
2021-12-09T12:33:35,715 [http-nio-8080-exec-6] WARN - Message handling or processing failed. [exception=(Unexpected code Response{protocol=http/1.1, code=400, message=, url=https://ids.db-connector.mobilitydataspace.io/api/ids/data} With Body: ---qxE0ZLbN72lHD0SPoL2ewOrlznFq4y8iq\r\nContent-Disposition: form-data; name="header"\r\nContent-Type: text/plain;charset=U...
```
and for the same error in the Swagger UI it says 500 as can be seen here:

![grafik](https://user-images.githubusercontent.com/4161673/145397737-ec0d8f62-f014-4605-8d8f-7b5c0ff2de13.png)

It doesn't help to discuss the error codes.

**Comment by ghost** [comment]
We jump back and forth here between different errors as well as DSC versions. The DSC version of the first post is not the same as from the last example. For the last example, I would recommend updating the DSC version you are using. The used version of the DSC receives a response with status 400, will then unfortunately in this version internally throw an Exception that the response was not in the successful-range. This response-not-successful-exception is caught internally again and passed on to the user as 500, that's the Swagger-UI response. This overall turns a received 400-response into an internal 500-error in the old version. This has already been fixed with the newer versions, for example the version from the first post in this issue logged only a warning and not an error.

It would be more interesting to know why there is a BAD_REQUEST as response overall.

**Comment by juliapampus** [comment]
Is this issue solved? @sebplorenz

**Comment by ghost** [comment]
_If I remember correctly: Went back to infomodel incompatibility between two running connectors. -> BAD_REQUEST as response_

**Comment by juliapampus** [comment]
Then I will close this issue, feel free to reopen.
