### ISSUE TITLE
417 EXPECTATION_FAILED

### ISSUE THREAD

**Issue by aniket-sketch** [FraunhoferISST/DataspaceConnector#840]
We are facing the below error while try to hit end point:   /api/ids/connector/update

Dataspace Connector Version : 6.5.2
DAPS Version:  1.16.0
Broker Version: 4.0.3

Error from Dataspace Connector : 
2022-01-13T10:38:27,257 [http-nio-8080-exec-9] [33mWARN[m - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=Could not extract class of child object. ID: true, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
2022-01-13T10:38:27,258 [http-nio-8080-exec-9] [34mDEBUG[m - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
2022-01-13T10:38:27,258 [http-nio-8080-exec-9] [34mDEBUG[m - Writing [{reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=Could not extract class of chil (truncated)...]
2022-01-13T10:38:27,258 [http-nio-8080-exec-9] [34mDEBUG[m - Closing JPA EntityManager in OpenEntityManagerInViewInterceptor
2022-01-13T10:38:27,259 [http-nio-8080-exec-9] [34mDEBUG[m - Completed 417 EXPECTATION_FAILED
2022-01-13T10:38:27,259 [http-nio-8080-exec-9] [34mDEBUG[m - onApplicationEvent: ServletRequestHandledEvent: url=[/ids62/api/ids/connector/update]; client=[20.76.244.127:12367]; method=[POST]; servlet=[dispatcherServlet]; session=[null]; user=[admin]; time=[662ms]; status=[OK]

Error From Broker : 
10:38:27.186 [http-nio-8080-exec-7] ERROR de.fraunhofer.iais.eis.ids.broker.core.common.persistence.RegistrationHandler - Failed to process message.
java.io.IOException: Could not extract class of child object. ID: true
        at de.fraunhofer.iais.eis.ids.jsonld.Parser.handleObject(Parser.java:70) ~[infomodel-serializer-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.jsonld.Parser.handleObject(Parser.java:548) ~[infomodel-serializer-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.jsonld.Parser.parseMessage(Parser.java:944) ~[infomodel-serializer-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.jsonld.Serializer.deserialize(Serializer.java:114) ~[infomodel-serializer-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.SelfDescriptionPersistenceAndIndexing.replaceIds(SelfDescriptionPersistenceAndIndexing.java:278) ~[open-broker-common-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.SelfDescriptionPersistenceAndIndexing.updated(SelfDescriptionPersistenceAndIndexing.java:316) ~[open-broker-common-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.RegistrationHandler.handleValidated(RegistrationHandler.java:92) ~[open-broker-common-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.RegistrationHandler.handleValidated(RegistrationHandler.java:25) ~[open-broker-common-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.connector.commons.messagevalidation.ValidatingMessageHandler.handle(ValidatingMessageHandler.java:28) ~[connector-commons-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:86) ~[core-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51) ~[core-4.0.3.jar!/:?]
        at java.util.Optional.map(Optional.java:265) [?:?]
        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51) [core-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45) [core-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87) [interaction-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237) [protocol-4.0.3.jar!/:?]
        at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205) [protocol-4.0.3.jar!/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) [javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) [javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.37.jar!/:9.0.37]

**Comment by ghost** [comment]
Summary:
Broker RegistrationHandler-class prints error "Failed to process message" because the used parser for incoming messages within the used infomodel-serializer (v4.0.3) throws an IOException "Could not extract class of child object. ID: true". -> Broker sends RejectionMessage as response with code INTERNAL_RECIPIENT_ERROR -> Dataspace Connector logs a warning for incoming RejectionMessage as response (everything else is debug-level)

Can you provide the message that the Dataspace Connector sent to the broker?

**Comment by juliapampus** [comment]
Is this still an issue @aniket-sketch?

**Comment by juliapampus** [comment]
Feel free to reopen, if this issue still exists with v7.
