### ISSUE TITLE
DSC 7.0.0 Clearing House logging

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#871]
Hi,
After migrating to version 7.0.0 I'm getting the following error when the DSC logs to the Clearing House:
```
2022-01-28 07:28:18,082 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Sending request to https://logging.test/messages/log/messages/log/bdd0c990-b326-4897-8a33-fbfe9757706e ...
2022-01-28 07:28:18,088 https-jsse-nio-8080-exec-5 WARN  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Received response but response-code not in 200-299. [code=(404)]
2022-01-28 07:28:18,089 https-jsse-nio-8080-exec-5 WARN  io.dataspaceconnector.service.message.builder.type.LogMessageService - Failed to send log message. [exception=(Received invalid ids message.)]
io.dataspaceconnector.common.exception.MessageResponseException: Received invalid ids message.
	at io.dataspaceconnector.service.message.builder.type.base.AbstractMessageService.send(AbstractMessageService.java:124) ~[classes!/:6.4.0]
	at io.dataspaceconnector.service.message.builder.type.LogMessageService.sendMessage(LogMessageService.java:82) [classes!/:6.4.0]
	at io.dataspaceconnector.common.ids.message.ClearingHouseService.logIdsMessage(ClearingHouseService.java:106) [classes!/:6.4.0]
	at io.dataspaceconnector.service.message.handler.ClearingHouseLoggingProcessor.process(ClearingHouseLoggingProcessor.java:54) [classes!/:6.4.0]
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66) [camel-support-3.12.0.jar!/:3.12.0]
```

**Comment by ghost** [comment]
The response code is 404 not found and looking at the address I could imagine that it isn't valid with two times `/messages/log`:
`https://logging.test/messages/log/messages/log/bdd0c990-b326-4897-8a33-fbfe9757706e`

**Comment by sebplorenz** [comment]
OK, I see in the logs that the 404 was already there with v6.4.0. It just didn't throw an exception.
